### ISSUE TITLE
Missing GET requests for 

### ISSUE THREAD

**Issue by birgerhaarbrandt** [ehrbase/fhir-bridge#257]
## Steps to reproduce ## 

Create a GET request for any resource in FHIR-Bridge

## Actual result ##

![fail](https://user-images.githubusercontent.com/2463423/109476760-8b32ef00-7a77-11eb-9ba2-0b8a7ed64ea7.png)

## Expected result ##

Should just provide back the correct resource. 

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by subigre** [comment]
I have implemented the search for Patient resource.

However I am encountering an issue for the other resources and I have not found yet the solution to be able to search using `subject.identifier`.

The problem is that HAPI FHIR JPA Server does not support search using the following JSON because the `identifier` is not indexed. 

```json
{
  "resourceType": "Observation",
  "subject": {
    "identifier": {
      "system": "urn:ietf:rfc:4122",
      "value": "07f602e0-579e-4fe3-95af-381728bf0d46"
    }
  }
}
```

**Comment by subigre** [comment]
The issue regarding `search` operation and [chained resource references](https://hapifhir.io/hapi-fhir/docs/server_plain/rest_operations_search.html#chained-resource-references) that are not working is due to the fact that we do not have a Patient resource linked to the given Observation.

```json
{
  "resourceType": "Observation",
  "subject": {
    "identifier": {
      "system": "urn:ietf:rfc:4122",
      "value": "{{patientId}}"
    }
  }
}
```

Using the example above, `Observation.subject.identifier` is not considered as a search parameter and is not indexed by the API.
`GET /Observation?subject.identifier={{patientId}}` => NO RESULT

However, the `search` feature works fine if the Observation resource is linked to an existing Patient patient:

```json
{
  "resourceType": "Patient",
  "identifier": {
    "system": "urn:ietf:rfc:4122",
    "value": "{{patientId}}"
  }
}
```
```json
{
  "resourceType": "Observation",
  "subject": {
    "reference": "/Patient/1"
  }
}
```
Using the previous example, the Observation is linked to the Patient and both are indexed. As a result, search using chained resource references returns the expected result.
`GET /Observation?subject.identifier={{patientId}}` => RESULT FOUND


The adopted solution is to use a `reference` in addition to the `identifier` like the in following example:
```json
{
  "resourceType": "Observation",
  "subject": {
    "reference": "/Patient?identifier=urn:ietf:rfc:4122|{{patientId}}",
    "identifier": {
      "system": "urn:ietf:rfc:4122",
      "value": "{{patientId}}"
    }
  }
}
```
Using this payload, the FHIR Bridge will first query the database in order to find the matching patient. If the Patient does not exist, it will create a new one and assign the provided identifier to it.
The following response is returned by the server:
```json
{
  "resourceType": "Observation",
  "subject": {
    "reference": "/Patient/1",
    "identifier": {
      "system": "urn:ietf:rfc:4122",
      "value": "{{patientId}}"
    }
  }
}
```
Finally, search operation works exactly as above.
`GET /Observation?subject.identifier={{patientId}}` => RESULT FOUND

⚠️ This solution requires to update the `MII-Reference` profile that prevents us to use a `reference` and an `identifier` at the same time.
