### ISSUE TITLE
OpenEHR Composition and startTimeValue

### ISSUE THREAD

**Issue by subigre** [ehrbase/fhir-bridge#273]
## Steps to reproduce ## 

@SevKohler and I discover some inconsistencies when `effective[x]` element is missing from the input FHIR resource in the Converter regarding the `startTimeValue`.

## Actual result ##
In some mappings:
```java
if (resourge.getEffectiveDateTime() == null) {
    throw new ConverterExcetion("No effective date time");
}
```
in some others
```java
if (resourge.getEffectiveDateTime() == null) {
    composition.setStartTimeValue(ZonedDateTime.now());
}
```

## Expected result ##

We should be coherent and use the same behaviour in all converters.
@birgerhaarbrandt, could you please tell us what is the expected behaviour? 

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by ppazos** [comment]
@subigre if this happens in the code:

```
if (resourge.getEffectiveDateTime() == null) {
    throw new ConverterExcetion("No effective date time");
}
```

It means the profile allows it, because if that code is reached, the validation worked. On that case, the mapping should work. So I would vote to remove those and set the date to now.

IMO the general criteria should be: if the profile validation of the resource works, the mapping should be successful, since all openEHR templates are based on those FHIR profiles. If there is an issue there, the template should be modified to comply. The only thing we can't modify is the underlying openEHR Reference Model.

**Comment by subigre** [comment]
@ppazos Many thanks for your reply. It make sense 👍

**Comment by SevKohler** [comment]
This should have been fixed with the newest refactoring can you check that @ppazos  @subigre
