### ISSUE TITLE
Description needed for adaption of new develop-branch-state

### ISSUE THREAD

**Issue by BirgitSaalfeld** [ehrbase/fhir-bridge#53]
I checked out the current develop branch and all tests are failing. 
Erik told me, that a new fhir_bridge-database is necessary with the port 9999 (from src/test/resources/application.yml)
```
    url: jdbc:postgresql://localhost:9999/fhir_bridge
    username: fhir_bridge
    password: fhir_bridge
```
So, I create the user and the db:
```
sudo -u postgres createuser -P -d fhir_bridge 
sudo -u postgres createdb -p 9999 fhir_bridge
```
But still the `mvn clean install` fails with all tests. How is it supposed to work? What can I do to make it work?

**Comment by subigre** [comment]
Dear @BirgitSaalfeld,
I suppose that if you have the PostgreSQL up and running, the problem comes from the missing EHRbase instance.
I am sorry because the current README.md is probably not clear enough and I have a PR (#43) under review in order to fix this problem.

The prerequisites to execute the integration tests (and build the app) are:
- A PostgreSQL database with the following configuration:
```
    url: jdbc:postgresql://localhost:9999/fhir_bridge
    username: fhir_bridge
    password: fhir_bridge
```
- An EHRbase instance with the following configuration:
```
  address: localhost
  port: 8080
  path: /ehrbase/rest/openehr/v1/
```

Currently, the easiest way to configure your local environment is to use the `docker-compose.yml` in the project root directory.

**Comment by BirgitSaalfeld** [comment]
There is no further error message when I use this command
```
docker run --name fhirdb -e POSTGRES_PASSWORD=fhir_bridge -e POSTGRES_USER=fhir_bridge -d -p 9999:5432 postgres
```
Correct me if I am wrong: 
This starts 
- a default postgres-database 
- names locally "fhirdb"
- with the user and password "fhir_bridge"
- maps from hostport 9999 to postgres default port 5432 in the docker environment

I don't see the connection to the fhirdb in the `docker-compose.yml` yet. 
Do you see anything that could be wrong with my setup or is that the way it is supposed to be?

**Comment by subigre** [comment]
It is strange because your configuration looks right. Do you have also a running EHRbase instance up and running?

The PR #43 as been merged and I think that the README.md is much more clear now.
You do not need PostgreSQL to build the application any more (only EHRbase server).

**Comment by BirgitSaalfeld** [comment]
The project works for me at the moment with the postgres-docker command. 
It doesn't work for me without it. 
Maybe I don't have enough knowledge about maven and the .yml-files to understand the readme fully. 

Because it works for the moment, I close this ticket now.
