### ISSUE TITLE
Missing Profile „QuelleKlinischesBezugsdatum“ in the Components of FHIR Bridge (CRR)

### ISSUE THREAD

**Issue by taneroksuz** [ehrbase/fhir-bridge#581]
## Steps to reproduce ## 

- We get error when we send our following FHIR bundle (test data) to CRR repostiory with BPE process (SendData):
[fhir-bundle.txt](https://github.com/ehrbase/fhir-bridge/files/9307230/fhir-bundle.txt)

- This error refers to following lines in our FHIR resources:
```xml
  <effectiveDateTime>
    <extension url="http://hl7.org/fhir/StructureDefinition/data-absent-reason">
      <valueCode value="unknown"/>
    </extension>
  </effectiveDateTime>
  ```

## Actual result ##

- BPE process provide the following commandline outputs when we send our FHIR Bundle:
```console
  bpe-app-1  | ERROR Grizzly(2) - LogValidationError.logValidationDetails(120) | CRR validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/9b22a43accacc42f46c8c69bfba896a547fa7c58f28336e98c97a1f3094af59b/_history/1 location Observation.effective.ofType(dateTime).extension[0]: Slicing cannot be evaluated: Problem with use of resolve() - profile [CanonicalType[https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum]] on Observation.effective[x].extension:QuelleKlinischesBezugsdatum could not be resolved (@char 1) 
  ```

## Expected result ##

- The validation tool of BPE process doesn't generate any validation error. So we are sure this error is related to components of FHIR Bridge (CRR). 

- This error can be fixed as wir replace the **extension** with following line:  
  ```json
  "effectiveDateTime": "1972-01-01T01:00:00+01:00"
  ```
- However both aforementioned values should be valid for this element of FHIR Bundle because the validation tool of BPE process reports no error.

## Success criteria ##

- [ ] The defect has been fixed

**Comment by hhund** [comment]
The FHIR Extension https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum is missing from the folder [src/main/resources/profiles](https://github.com/ehrbase/fhir-bridge/tree/master/src/main/resources/profiles) but needed for validating resources with the following profiles:
* [https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/ObservationLab.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-ab-ser-pl-ia-acnc](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2AbSerPlIAaCnc.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-iga-ser-pl-ql-ia](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2IgASerPlQlIA.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-ab-ser-pl-ql-ia](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2AbSerPlQlIA.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-igm-ser-pl-ql-ia](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2IgMSerPlQlIA.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-igg-ser-pl-ql-ia](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2IgGSerPlQlIA.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-igm-ser-pl-ia-acnc](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2IgMSerPlIAaCnc.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-iga-ser-pl-ia-acnc](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2IgASerPlIAaCnc.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-igg-ser-pl-ia-acnc](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2IgGSerPlIAaCnc.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-rt-pcr](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/SarsCoV2RTPCR.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/carbon-dioxide-partial-pressure](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/GasPanel-PaCO2.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/oxygen-partial-pressure](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/GasPanel-PaO2.xml)
* [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/inhaled-oxygen-concentration](https://github.com/ehrbase/fhir-bridge/blob/master/src/main/resources/profiles/FiO2.xml)

**Comment by taneroksuz** [comment]
- In the meantime the CRR is updated. Unfortunately we get another error based on the same FHIR element as follows:
  ````console
  bpe-app-1  | ERROR Grizzly(2) - LogValidationError.logValidationDetails(120) | CRR validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/9b22a43accacc42f46c8c69bfba896a547fa7c58f28336e98c97a1f3094af59b/_history/1: StructureDefinition https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum has no snapshot, and no snapshot generator is configured
  ````

**Comment by SevKohler** [comment]
@taneroksuz could you please provide me a more specific sample set of what is failing. 
The bundle you provided has 10k lines. 
I wont be able to debug that since i will have to split it manually which will take hours. 
Could you guys provide me a more specific sample set so i can test and fix the bug, thanks. 
PS: i had vacation now im back. 

Branch: https://github.com/ehrbase/fhir-bridge/tree/fix_581

**Comment by hhund** [comment]
@SevKohler This issue has been fixed in the version / fork running in the NUM-CODEX CRR pre prod and prod installations. You may want to talk to itos@vitagroup.ag

Also I would suggest reading up on how FHIR validation typically works and why snapshots of all StructureDefinitions referenced by a profile, against the validation is performed, are needed at runtime. In my earlier comment I listed all profiles requiring the `QuelleKlinischesBezugsdatum` extension, but other StructureDefinitions resources might be missing as well.

Example resources for all GECCO profiles can be found in the `de.gecco` FHIR implementation guide: https://simplifier.net/ForschungsnetzCovid-19

**Comment by SevKohler** [comment]
@hhund did you took a look who comitted most of the code for the fhir bridge ?
If you would assume that i dont know that, i think we would have much bigger problems then just simply forgetting to copy paste an extensions lol. 
And yes it may occur again, but usually i added all extensions. 

About who does what:
1. vita takes care about server CI prepod etc. 
2. I (sadly its currently only me) take care for the other stuff mainly mappings and partly the validation. 

In this case vita fixed it for their prepod since i was not in the office for 4 weeks.
So in the future (if related to mappings or in general fhir and openEHR), if time pressures just write me an mail or directly assign the issues to me so i can clearly see it. Otherwise, you can also write vita but usually it ends up on my desk anyways (if its my responsibility).
