### ISSUE TITLE
FIO2 url changed to "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/inhaled-oxygen-concentration"

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/fhir-bridge#81]
## Steps to reproduce ## 

FIO2 changed from "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/FIO2" to "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/inhaled-oxygen-concentration".

See https://simplifier.net/forschungsnetzcovid-19/observation-fio2

## Actual result ##
 Tests fail

## Expected result ##

Tests work

Describe the expected output / behaviour.

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by SevKohler** [comment]
I fixed it now as part of feature60/bloodgas, if not i get errors, are there any objections in doing so ?

**Comment by SevKohler** [comment]
@ppazos fixed in pull [request](https://github.com/ehrbase/fhir-bridge/pull/86)

**Comment by SevKohler** [comment]
Tests still work if replacing the current test dataset with the new example data set. But you are right i will take it out and make an new issue.

**Comment by ppazos** [comment]
@SevKohler I think it's OK to maintain all changes in the same PR since you need the FiO2 for your mappings.

Though I think we need to integrate the newest profile, with the new ID/URI and new dataset compliant with that, remove the previous one and retest the mapping is working OK and we don't need to change the code of the mapping itself.

**Comment by SevKohler** [comment]
This is already done in the PR, nevertheless the tests do not check the actual outcome of the mapping, its better to take a closer look and check if there are new fields for FiO2 or so. This i why i asked @ErikTute, who did the initial FIO2 mapping, to check again if everything is fine.

**Comment by wlad** [comment]
@SevKohler please link this (and if applicable also other) ticket(s) in the PR so that they get closed automatically when the PR is merged

i.e. ad somethink like this in PR's description:

fixes #81

Is a best practice to apply in all PRs actually.

see [this Github Docs](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for details
